# Generated by Django 3.2.8 on 2023-11-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panaderia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panes',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
