# Generated by Django 3.2.8 on 2023-11-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Panaderia', '0003_rename_panes_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=50)),
                ('sueldo', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
            ],
        ),
    ]
