# Generated by Django 3.2.8 on 2023-11-20 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Panaderia', '0004_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='cargo',
            new_name='ocupacion',
        ),
    ]
